USE TSA;
SELECT *FROM NOBEL_WIN;
--  WRITE A SQL QUERY TO FIND THE NOBLE PRIZE WINNER(S) for the year 1978, return counrty, year , subject and winner -- 
SELECT COUNTRY,YEAR, SUBJECT,WINNER FROM NOBEL_WIN WHERE YEAR = (1978);
--  WRITE A SQL QUERY TO FIND THE NOBEL PRIZE WINNER IN 'LITERATURE' FOR 1987.RETURN WINNER, COUNRTY-- 
SELECT WINNER, COUNTRY FROM NOBEL_WIN WHERE SUBJECT= "LITERATURE" AND YEAR= (1987);
-- WRITE A SQL QUERY TO OCATE THE NOBLE PRIZE WINNERS IN 'DENNIS GABOR' RETURN ALL RECORD-- 
SELECT * FROM NOBEL_WIN WHERE WINNER = "DENNIS GABOR";
-- WRITE A SQL QUERY TO FIND THE NOBEL PRIZE WINNER IN 'CHEMISTRY' BETWEEN THE YEAR 1965 AND 1975. BEGIN AND END VALUES ARE INCLUDED. RETURN YEAR, SUBJECT,WINNER,AND COUNTRY-- 
SELECT SUBJECT, YEAR,WINNER,COUNTRY FROM NOBEL_win 
WHERE SUBJECT ="CHEMISTRY" AND YEAR BETWEEN 1965 AND 1975;
-- WRITE A SQL QUERY TO DISPLAY ALL DETAILS OF THE PRIME MINITERIAL WINNERS AFTER 1972 OF MENACHEM BEGIN AND YITZHAK RABIN--  
SELECT * FROM NOBEL_WIN WHERE CATEGORY = "PRIME MINISTER" AND YEAR > 1972;
-- WRITE A SQL  QUERY TO RETRIVE THE DETAILS OF THE WINNERS WHOSE FIRST NAMES MATCH WITH THE STRING 'SIMON'. RETURN YEAR,SUBJECT,WINNER,COUNTRY,AND CATEGORY--
SELECT YEAR, SUBJECT,WINNER,COUNTRY,CATEGORY FROM NOBEL_WIN WHERE WINNER LIKE "%SIMON%";
-- WRITE A SQL QUERY THAT COMBINES THE WINNERS IN LITERATURE,1971 AND IN ECONMICS,1971. RETURN YEAR,SUBJECT,COUNTRY, WINNER,AND CATEGORY-- 
SELECT * FROM NOBEL_WIN WHERE SUBJECT = "LITERATURE" AND YEAR = 1971
UNION
SELECT * FROM NOBEL_WIN WHERE SUBJECT = "ECONOMICS" AND YEAR = 1971;
-- WRITE  A SQL QUERY TO FIND THE NOBEL  PRIZE WINNERS IN 1970 EXCLUDING  THE SUBJECTS OF PHYSIOLOGY AND ECONMICS. RETURN YEARE,SUBJECT,WINNER,COUNTRY AND CATEGORY-- 
SELECT * FROM NOBEL_WIN WHERE YEAR =1970 AND SUBJECT != "ECONOMICS" and SUBJECT!= "physiology";
-- FIND NOBLE PRIZE WINNERS FOR THE SUBJECT THAT DOES NOT BEGIN WITH THE LETTER 'L'.RETURN YEAR, SUBJECT,WINNER,COUNTRY AND CATEGORY. ORDER THE RESULT BY YEAR, DESCENDING--
SELECT * FROM NOBEL_WIN WHERE SUBJECT != "L" ORDER BY YEAR DESC;   
-- WRITE A SQL QUERY TO COMBINE THE WINNERS IN 'PHYSIOLOGY' BEFORE 1971 AND WINNERS IN 'PEACE' ON OR AFTER, SUBJECT,WINNER, COUNRTY AND CATEGORY -- 
 SELECT * FROM NOBEL_WIN WHERE SUBJECT = "PHYSIOLOGY" AND YEAR < 1971 AND SUBJECT ="PEACE"
 UNION
 SELECT * FROM NOBEL_WIN WHERE YEAR >=1974;
 -- WRITE A SQL QUERY TO FIND THE DETAILS OF THE NOBLE PRIZE WINNER 'JOHANNES GEORG BEDNORZ'. RETURN ,YEAR, SUBJECT, WINNER, COUNTRY AND CATEGORY-- 
 SELECT * FROM NOBEL_WIN WHERE WINNER = "JOHANNES GEORG BEDNORZ";
 -- WRITE A SQL QUERY TO FIND NOBEL PRIZE WINNERS FOR THE SUBJECT THAT DOES NOT BEGIN WITH THE LETTER 'P'. RETURN YEAR, SUBJECT ,WINNER , COUNTRY, AND CATEGORY . ORDER THE RESULT BY YEAR , DESC AND WINNER IN ASC -- 
 